include:
  - project: 'ledgity/root'
    ref: master
    file: '/templates/.gitlab-ci-traefik-tmpl.yml'

default:
  tags:
    - docker

## Stages declarations

setup_for_prod:
  extends: .setup_tmpl
  variables:
    FLAVOR: prod
  only:
    - master

build_app:
  extends: .build_tmpl

deploy:
  extends: .deploy_tmpl
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
